#!/usr/bin/env bash
#
# USAGE
#	k8s-deploy DOCKER_REPO [DEPLOY_DIR]
#
# ARGUMENTS
#	1. DOCKER_REPO    Name of docker repository to push docker image to
#	2. DEPLOY_DIR     Directory which holds Helm packages. Each directory in 
#                     the DEPLOY_DIR must be a Helm package.

# git_head get git HEAD sha
function git_head() {
	echo $(git rev-parse --verify HEAD)
}

# Arguments
docker_repo="$1"
if [ -z "$docker_repo" ]; then
	echo "Error: DOCKER_REPO argument must be provided" >&2
	exit 1
fi

# Build docker image
echo "Building docker image"

if ! git_head | read version; then
	echo "Error: failed to get git head sha" >&2
	exit 1
fi

docker_tag="$docker_repo:$version"

docker build -t "$docker_tag" .

# Push docker image
echo "Pushing docker image"
docker push "$docker_tag"

# 
